#!/bin/bash
# Autostart for i3
# by MrGreen [mrgreen@archbang.org]

# Background
feh --no-fehbg --bg-scale ~/Pictures/Backgrounds/background.png &

# Network Manager Applet
(sleep 2 && nm-applet) &

# Volume
(sleep 2 && volumeicon) &

# Dunst onscreen messages
(sleep 2 && dunst) &

# Battery icon
(sleep 2 && cbatticon -n) &

# Xorg keyboard map change for your own country/keyboard layout
setxkbmap us &
